complete_data <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data <- subset(complete_data,Date %in% c('1/2/2007','2/2/2007'))
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
datetime <- paste(as.Date(data$Date), data$Time)
data$Datetime <- as.POSIXct(datetime)
with(data,{
  plot(Sub_metering_1~Datetime,type="l",ylab="Energy sub metering")
  lines(Sub_metering_2~Datetime,col="red")
  lines(Sub_metering_3~Datetime,col="blue")
})
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=1, lwd=2)
dev.copy(png, file="plot3.png", height=480, width=480)
dev.off()