complete_data <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data <- subset(complete_data,Date %in% c('1/2/2007','2/2/2007'))
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
hist(data$Global_active_power,col = "red",main="Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.copy(png,file="plot1.png", width=480, height=480)
dev.off()
